### ISSUE TITLE
Issues with other networked automation services.

### ISSUE THREAD

**Issue by sarcasticsapien** [mariusmotea/diyHue#8]
Maybe not so much an issue, but for what it's worth, the bridge emulator doesn't seem to play well with other networked automation services I have running on my network.
My network includes Home Assistant (home-assistant.io), ~~Hyperion.ng (github.com/hyperion-project/hyperion.ng),~~ and a Philips Hue Bridge 2G.
Home Assistant gets a little finicky and has to be restarted multiple times (at times) to find the real Philips Bridge and the Emulated Bridge. (Also, using automations in Home Assistant, the lights controlled through the Emulated Bridge have a few different reactions than the Hue lights controlled through the Hue Bridge.)
~~Hyperion.ng often has issues with the Proto server/client communication. (I run 2 Hyperion.ng servers for extra effects across the room. Shortly after starting Hyperion.ng, it usually freezes and throws errors about not being able to communicate via Proto. Once I stopped the Emulated Bridge, I had no issues.~~

I'm not really expecting you to troubleshoot these or correct them, just sharing my experience.

With all of that said, when it comes to just wanting to use your Emulated Bridge with a couple of strip lights on some D1 mini's and controlling them from the Hue app, it works great! So essentially, it works as is intended in that sense. Nice work!

EDIT: Redacted appears to be a different issue now, unrelated to the emulated bridge, just coincidental timing.

**Comment by mariusmotea** [comment]
Hi,

Where there are issues with real Philips Bridge most likely the issue is on client app side so nothing can be done from my side. Where the emulated bridge is not behave like a real bridge then i can fix this, but most likely i will need some help because i don't have a Philips Hue system in my home to see exactly the differences. I will try to install home-assistant and hyperion, maybe i will see some new request that i don't add to my emulator.

**Comment by sarcasticsapien** [comment]
After further investigation, there may not be a conflict with hyperion.ng... After I stopped your emulated bridge and restarted my hyperion.ng, it was working again so I assumed it was related to the emulated bridge, but now it appears my wifi dongle on the pi zero may be going out (just happened to start when I was testing your bridge).

I have a new usb -> ethernet adapter on the way for that pi, so I will confirm tomorrow.  For now I will remove that from my original post.


As far as performance differences between the real Philips Hue and Emulated Bridge with Home-Assistant:
I have 1 Hue LightStrip Plus and 1 Hue Motion Detector set up with automation on my Home-Assistant. The Hue LightStrip is above cabinets in my kitchen. The automation is set so that when there is motion, the lights come on. After 4min 30sec, the LightStrip dims to 50%, and then after another 30sec, the LightStrip turns off. I created a second light strip with your Emulated Bridge and a D1 mini to put over my other cabinets and control with the same automation in Home-Assistant. The emulated lights do not act in the same way as the Hue LightStrip. When there is motion, the lights do come on, but if there is motion again, before the lights automate off, the emulated lights flash off and then back on.  So if I walk into my kitchen, the lights come on. If I stand still (or not enough movement for the motion sensor) for a few seconds, then move again (while the lights are still on), the motion sensor triggers again... The Hue LightStrip remains at the same brightness, so no visible changes, but the emulated light strip will flash off and then immediately back on.

Also, when the emulated light strip automates to off, it flashes white before fading out to off. The Hue LightStrip just fades out to off.

I have a MakerFocus D1 mini connected to a SK6812 (128 leds, 60/m), all powered from a 5v 20A power supply.

**Comment by mariusmotea** [comment]
Hi,
I don't recommend to run a bridge connected over wi-fi, i saw big differences with an Orange pi Zero that has both wi-fi and ethernet and i believe this is the main reason why Philips, Ikea bridge/gateway provide ethernet connection only. Regarding what you describe here, the behaviour is very strange for dimming operation. Please ensure that you use latest HueEmulator.py file from this repo because i push updates very fast and last weekend i made a few commits with bugs fix. If this don't solve the issue, i cannot replicate your setup but you could execute HueEmulator.py manually and provide me the output at moment "4min 30sec" when instead to have a nice dimming to 50% you have a light restart. With your output i can send same commands with curl and replicate the issue.
The white flash before fading out i believe is because you use PWM generic sketch with startup option "Last state". This require to write the light state into eeprom and ESP8266 has this strange behaviour during this operation. In your case i believe this can se set to Off with no problems. Also ensure that you use latest sketch in your light.

**Comment by sarcasticsapien** [comment]
I ended up installing HueEmulator on a Pi Zero W (since my Pi 3 has HomeAssistant running with it's own emulated hue bridge).
I changed the light's last state to off... It seems that when ever I turn the emulated hue light off with HomeAssistant, it flashes white before fading off (in white). Looking at the output from HueEmulator, it seems that when ever I turn it off from HomeAssistant, the alert command is also processing (but doesn't from the Hue App):
`
10.0.1.15 - - [10/Jun/2017 16:03:29] "PUT /api/376169333a8f86f59a543592a68d7017eb37da84/lights/1/state HTTP/1.1" 200 -
in PUT method
[
    {
        "success": {
            "/lights/1/state/on": false
        }
    },
    {
        "success": {
            "/lights/1/state/alert": "none"
        }
    }
]
`

**Comment by mariusmotea** [comment]
I understand what is the problem and i will solve tomorrow. I implement alert because it help me to identify the lights from official application, but is at a very basic level, it don't care about the value that is passed, if is a request with alert key then the light will flash. I will change this to ignore if alert value is "none", like in your pasted output.
Thanks,
Marius.

**Comment by mariusmotea** [comment]
Fixed in #12 . Just flash again the light firmware.

**Comment by sarcasticsapien** [comment]
I downloaded the most recent and flashed light firmware... tested and the same thing still happens. Then I clicked into the Lights folder on github and see that you updated the Arduino files.  I've been uploading PlatformIO with Atom.

I'll try to get my Arduino set up later tonight (after my run and dinner) to flash that way.

**Comment by sarcasticsapien** [comment]
Got it flashed with Arduino.
That fixed the flashing issue, the light now fades out in its assigned color as it should, from HomeAssistant.
Thanks for that fix!

**Comment by mariusmotea** [comment]
Thanks for testing! Glad to hear it's working. Feel free to re-open if you notice anything else.
